# **Open the user and activity datasets**

In [5]:
import numpy as np
import pandas as pd

In [6]:
from google.colab import files
files.upload()

Saving Book3.csv to Book3.csv

{'Book3.csv': b'\xef\xbb\xbfuser,gender,age,disability,disability_type,mental_illness,illness_type,activity,rating\r\n1,Female,18,no,,yes,depression,Board games,3\r\n1,Female,18,no,,yes,depression,Cooking,4\r\n1,Female,18,no,,yes,depression,Walking,5\r\n1,Female,18,no,,yes,depression,Reading,4\r\n1,Female,18,no,,yes,depression,Puzzles,3\r\n1,Female,18,no,,yes,depression,Craft,4\r\n1,Female,18,no,,yes,depression,Running,5\r\n1,Female,18,no,,yes,depression,Basketball,4\r\n1,Female,18,no,,yes,depression,Football,4\r\n1,Female,18,no,,yes,depression,Volleyball,4\r\n1,Female,18,no,,yes,depression,Cricket,3\r\n1,Female,18,no,,yes,depression,Hockey,3\r\n1,Female,18,no,,yes,depression,Badminton,4\r\n1,Female,18,no,,yes,depression,Tennis,4\r\n1,Female,18,no,,yes,depression,Table Tennis,4\r\n1,Female,18,no,,yes,depression,Attend Workshops or Conference,3\r\n1,Female,18,no,,yes,depression,Woodworking Class,4\r\n1,Female,18,no,,yes,depression,Pottery Class,5\r\n1,Female,18,no,,yes,depression,Movie,3\r\n1,Female,18,no,,yes,depression,Game night,3\r\n1,Female,18,no,,yes,depression,Dance,4\r\n1,Female,18,no,,yes,depression,Music,5\r\n1,Female,18,no,,yes,depression,Yoga and Acrobatics,5\r\n1,Female,18,no,,yes,depression,Community Gardening,5\r\n2,Male,45,no,,no,,Board games,4\r\n2,Male,45,no,,no,,Cooking,3\r\n2,Male,45,no,,no,,Walking,3\r\n2,Male,45,no,,no,,Reading,3\r\n2,Male,45,no,,no,,Puzzles,2\r\n2,Male,45,no,,no,,Craft,2\r\n2,Male,45,no,,no,,Running,5\r\n2,Male,45,no,,no,,Basketball,5\r\n2,Male,45,no,,no,,Football,4\r\n2,Male,45,no,,no,,Volleyball,5\r\n2,Male,45,no,,no,,Cricket,4\r\n2,Male,45,no,,no,,Hockey,4\r\n2,Male,45,no,,no,,Badminton,4\r\n2,Male,45,no,,no,,Tennis,5\r\n2,Male,45,no,,no,,Table Tennis,5\r\n2,Male,45,no,,no,,Attend Workshops or Conference,3\r\n2,Male,45,no,,no,,Woodworking Class,3\r\n2,Male,45,no,,no,,Pottery Class,4\r\n2,Male,45,no,,no,,Movie,4\r\n2,Male,45,no,,no,,Game night,2\r\n2,Male,45,no,,no,,Dance,1\r\n2,Male,45,no,,no,,Music,4\r\n2,Male,45,no,,no,,Yoga and Acrobatics,3\r\n2,Male,45,no,,no,,Community Gardening,2\r\n4,Male,23,yes,visual,yes,anxiety,Board games,2\r\n4,Male,23,yes,visual,yes,anxiety,Cooking,3\r\n4,Male,23,yes,visual,yes,anxiety,Walking,5\r\n4,Male,23,yes,visual,yes,anxiety,Reading,0\r\n4,Male,23,yes,visual,yes,anxiety,Puzzles,2\r\n4,Male,23,yes,visual,yes,anxiety,Craft,2\r\n4,Male,23,yes,visual,yes,anxiety,Running,3\r\n4,Male,23,yes,visual,yes,anxiety,Basketball,0\r\n4,Male,23,yes,visual,yes,anxiety,Football,0\r\n4,Male,23,yes,visual,yes,anxiety,Volleyball,0\r\n4,Male,23,yes,visual,yes,anxiety,Cricket,0\r\n4,Male,23,yes,visual,yes,anxiety,Hockey,0\r\n4,Male,23,yes,visual,yes,anxiety,Badminton,0\r\n4,Male,23,yes,visual,yes,anxiety,Tennis,0\r\n4,Male,23,yes,visual,yes,anxiety,Table Tennis,0\r\n7,Male,33,no,,yes,neurodevelopmental,Board games,3\r\n7,Male,33,no,,yes,neurodevelopmental,Cooking,4\r\n7,Male,33,no,,yes,neurodevelopmental,Walking,5\r\n7,Male,33,no,,yes,neurodevelopmental,Reading,5\r\n7,Male,33,no,,yes,neurodevelopmental,Puzzles,4\r\n7,Male,33,no,,yes,neurodevelopmental,Craft,4\r\n8,Female,23,yes,hearing,yes,anxiety,Board games,2\r\n8,Female,23,yes,hearing,yes,anxiety,Cooking,2\r\n8,Female,23,yes,hearing,yes,anxiety,Walking,4\r\n8,Female,23,yes,hearing,yes,anxiety,Reading,5\r\n8,Female,23,yes,hearing,yes,anxiety,Puzzles,4\r\n8,Female,23,yes,hearing,yes,anxiety,Craft,2\r\n8,Female,23,yes,hearing,yes,anxiety,Running,5\r\n8,Female,23,yes,hearing,yes,anxiety,Basketball,4\r\n8,Female,23,yes,hearing,yes,anxiety,Football,5\r\n8,Female,23,yes,hearing,yes,anxiety,Volleyball,5\r\n8,Female,23,yes,hearing,yes,anxiety,Cricket,3\r\n8,Female,23,yes,hearing,yes,anxiety,Hockey,2\r\n8,Female,23,yes,hearing,yes,anxiety,Badminton,3\r\n8,Female,23,yes,hearing,yes,anxiety,Tennis,5\r\n8,Female,23,yes,hearing,yes,anxiety,Table Tennis,4\r\n9,Male,77,yes,hearing,yes,depression,Board games,3\r\n9,Male,77,yes,hearing,yes,depression,Cooking,4\r\n9,Male,77,yes,hearing,yes,depression,Walking,3\r\n9,Male,77,yes,hearing,yes,depression,Reading,5\r\n9,Male,77,yes,hearing,yes,depression,Puzzles,4\r\n9,Male,77,yes,hearing,yes,depression,Craft,1\r\n9,Male,77,yes,hearing,yes,depression,Running,1\r\n9,Male,77,yes,hearing,yes,depression,Basketball,2\r\n9,Male,77,yes,hearing,yes,depression,Football,3\r\n9,Male,77,yes,hearing,yes,depression,Volleyball,4\r\n9,Male,77,yes,hearing,yes,depression,Cricket,4\r\n9,Male,77,yes,hearing,yes,depression,Hockey,3\r\n9,Male,77,yes,hearing,yes,depression,Badminton,4\r\n9,Male,77,yes,hearing,yes,depression,Tennis,5\r\n9,Male,77,yes,hearing,yes,depression,Table Tennis,2\r\n9,Male,77,yes,hearing,yes,depression,Attend Workshops or Conference,1\r\n9,Male,77,yes,hearing,yes,depression,Woodworking Class,4\r\n9,Male,77,yes,hearing,yes,depression,Pottery Class,3\r\n9,Male,77,yes,hearing,yes,depression,Movie,0\r\n9,Male,77,yes,hearing,yes,depression,Game night,0\r\n9,Male,77,yes,hearing,yes,depression,Dance,2\r\n9,Male,77,yes,hearing,yes,depression,Music,0\r\n9,Male,77,yes,hearing,yes,depression,Yoga and Acrobatics,4\r\n9,Male,77,yes,hearing,yes,depression,Community Gardening,3\r\n10,Male,19,no,,yes,anxiety,Board games,3\r\n10,Male,19,no,,yes,anxiety,Cooking,4\r\n10,Male,19,no,,yes,anxiety,Walking,5\r\n10,Male,19,no,,yes,anxiety,Reading,4\r\n10,Male,19,no,,yes,anxiety,Puzzles,3\r\n10,Male,19,no,,yes,anxiety,Craft,5\r\n10,Male,19,no,,yes,anxiety,Running,4\r\n10,Male,19,no,,yes,anxiety,Basketball,3\r\n10,Male,19,no,,yes,anxiety,Football,2\r\n10,Male,19,no,,yes,anxiety,Volleyball,4\r\n10,Male,19,no,,yes,anxiety,Cricket,2\r\n10,Male,19,no,,yes,anxiety,Hockey,5\r\n10,Male,19,no,,yes,anxiety,Badminton,4\r\n10,Male,19,no,,yes,anxiety,Tennis,2\r\n10,Male,19,no,,yes,anxiety,Table Tennis,5\r\n3,Male,37,yes,visual,yes,neurodevelopmental,Board games,4\r\n3,Male,37,yes,visual,yes,neurodevelopmental,Cooking,3\r\n3,Male,37,yes,visual,yes,neurodevelopmental,Walking,2\r\n3,Male,37,yes,visual,yes,neurodevelopmental,Reading,0\r\n3,Male,37,yes,visual,yes,neurodevelopmental,Puzzles,4\r\n3,Male,37,yes,visual,yes,neurodevelopmental,Craft,5\r\n5,Female,17,yes,visual,yes,depression,Board games,1\r\n5,Female,17,yes,visual,yes,depression,Cooking,2\r\n5,Female,17,yes,visual,yes,depression,Walking,4\r\n5,Female,17,yes,visual,yes,depression,Reading,0\r\n5,Female,17,yes,visual,yes,depression,Puzzles,1\r\n5,Female,17,yes,visual,yes,depression,Craft,2\r\n5,Female,17,yes,visual,yes,depression,Running,5\r\n5,Female,17,yes,visual,yes,depression,Basketball,0\r\n5,Female,17,yes,visual,yes,depression,Football,0\r\n5,Female,17,yes,visual,yes,depression,Volleyball,0\r\n5,Female,17,yes,visual,yes,depression,Cricket,0\r\n5,Female,17,yes,visual,yes,depression,Hockey,0\r\n5,Female,17,yes,visual,yes,depression,Badminton,0\r\n5,Female,17,yes,visual,yes,depression,Tennis,0\r\n5,Female,17,yes,visual,yes,depression,Table Tennis,0\r\n5,Female,17,yes,visual,yes,depression,Attend Workshops or Conference,4\r\n5,Female,17,yes,visual,yes,depression,Woodworking Class,3\r\n5,Female,17,yes,visual,yes,depression,Pottery Class,4\r\n5,Female,17,yes,visual,yes,depression,Movie,1\r\n5,Female,17,yes,visual,yes,depression,Game night,3\r\n5,Female,17,yes,visual,yes,depression,Dance,4\r\n5,Female,17,yes,visual,yes,depression,Music,5\r\n5,Female,17,yes,visual,yes,depression,Yoga and Acrobatics,4\r\n5,Female,17,yes,visual,yes,depression,Community Gardening,5\r\n6,Female,60,yes,hearing,yes,neurodevelopmental,Board games,3\r\n6,Female,60,yes,hearing,yes,neurodevelopmental,Cooking,4\r\n6,Female,60,yes,hearing,yes,neurodevelopmental,Walking,4\r\n6,Female,60,yes,hearing,yes,neurodevelopmental,Reading,3\r\n6,Female,60,yes,hearing,yes,neurodevelopmental,Puzzles,1\r\n6,Female,60,yes,hearing,yes,neurodevelopmental,Craft,4\r\n11,Male,13,yes,mobility,yes,depression,Board games,4\r\n11,Male,13,yes,mobility,yes,depression,Cooking,3\r\n11,Male,13,yes,mobility,yes,depression,Walking,1\r\n11,Male,13,yes,mobility,yes,depression,Reading,5\r\n11,Male,13,yes,mobility,yes,depression,Puzzles,4\r\n11,Male,13,yes,mobility,yes,depression,Craft,3\r\n11,Male,13,yes,mobility,yes,depression,Running,0\r\n11,Male,13,yes,mobility,yes,depression,Basketball,0\r\n11,Male,13,yes,mobility,yes,depression,Football,0\r\n11,Male,13,yes,mobility,yes,depression,Volleyball,0\r\n11,Male,13,yes,mobility,yes,depression,Cricket,1\r\n11,Male,13,yes,mobility,yes,depression,Hockey,0\r\n11,Male,13,yes,mobility,yes,depression,Badminton,1\r\n11,Male,13,yes,mobility,yes,depression,Tennis,0\r\n11,Male,13,yes,mobility,yes,depression,Table Tennis,2\r\n11,Male,13,yes,mobility,yes,depression,Attend Workshops or Conference,4\r\n11,Male,13,yes,mobility,yes,depression,Woodworking Class,4\r\n11,Male,13,yes,mobility,yes,depression,Pottery Class,5\r\n11,Male,13,yes,mobility,yes,depression,Movie,3\r\n11,Male,13,yes,mobility,yes,depression,Game night,2\r\n11,Male,13,yes,mobility,yes,depression,Dance,1\r\n11,Male,13,yes,mobility,yes,depression,Music,5\r\n11,Male,13,yes,mobility,yes,depression,Yoga and Acrobatics,0\r\n11,Male,13,yes,mobility,yes,depression,Community Gardening,4\r\n14,Non-binary,36,yes,mobility,yes,neurodevelopmental,Board games,5\r\n14,Non-binary,36,yes,mobility,yes,neurodevelopmental,Cooking,3\r\n14,Non-binary,36,yes,mobility,yes,neurodevelopmental,Walking,1\r\n14,Non-binary,36,yes,mobility,yes,neurodevelopmental,Reading,4\r\n14,Non-binary,36,yes,mobility,yes,neurodevelopmental,Puzzles,3\r\n14,Non-binary,36,yes,mobility,yes,neurodevelopmental,Craft,5\r\n12,Female,47,yes,mobility,yes,anxiety,Board games,1\r\n12,Female,47,yes,mobility,yes,anxiety,Cooking,4\r\n12,Female,47,yes,mobility,yes,anxiety,Walking,2\r\n12,Female,47,yes,mobility,yes,anxiety,Reading,5\r\n12,Female,47,yes,mobility,yes,anxiety,Puzzles,5\r\n12,Female,47,yes,mobility,yes,anxiety,Craft,3\r\n12,Female,47,yes,mobility,yes,anxiety,Running,0\r\n12,Female,47,yes,mobility,yes,anxiety,Basketball,0\r\n12,Female,47,yes,mobility,yes,anxiety,Football,0\r\n12,Female,47,yes,mobility,yes,anxiety,Volleyball,0\r\n12,Female,47,yes,mobility,yes,anxiety,Cricket,0\r\n12,Female,47,yes,mobility,yes,anxiety,Hockey,0\r\n12,Female,47,yes,mobility,yes,anxiety,Badminton,0\r\n12,Female,47,yes,mobility,yes,anxiety,Tennis,0\r\n12,Female,47,yes,mobility,yes,anxiety,Table Tennis,2\r\n15,Male,16,yes,mobility,no,,Board games,5\r\n15,Male,16,yes,mobility,no,,Cooking,4\r\n15,Male,16,yes,mobility,no,,Walking,0\r\n15,Male,16,yes,mobility,no,,Reading,3\r\n15,Male,16,yes,mobility,no,,Puzzles,2\r\n15,Male,16,yes,mobility,no,,Craft,2\r\n15,Male,16,yes,mobility,no,,Running,0\r\n15,Male,16,yes,mobility,no,,Basketball,0\r\n15,Male,16,yes,mobility,no,,Football,0\r\n15,Male,16,yes,mobility,no,,Volleyball,0\r\n15,Male,16,yes,mobility,no,,Cricket,0\r\n15,Male,16,yes,mobility,no,,Hockey,0\r\n15,Male,16,yes,mobility,no,,Badminton,0\r\n15,Male,16,yes,mobility,no,,Tennis,0\r\n15,Male,16,yes,mobility,no,,Table Tennis,0\r\n15,Male,16,yes,mobility,no,,Attend Workshops or Conference,3\r\n15,Male,16,yes,mobility,no,,Woodworking Class,4\r\n15,Male,16,yes,mobility,no,,Pottery Class,5\r\n15,Male,16,yes,mobility,no,,Movie,3\r\n15,Male,16,yes,mobility,no,,Game night,4\r\n15,Male,16,yes,mobility,no,,Dance,2\r\n15,Male,16,yes,mobility,no,,Music,0\r\n15,Male,16,yes,mobility,no,,Yoga and Acrobatics,1\r\n15,Male,16,yes,mobility,no,,Community Gardening,0\r\n13,Female,68,yes,hearing,no,,Board games,2\r\n13,Female,68,yes,hearing,no,,Cooking,3\r\n13,Female,68,yes,hearing,no,,Walking,5\r\n13,Female,68,yes,hearing,no,,Reading,4\r\n13,Female,68,yes,hearing,no,,Puzzles,3\r\n13,Female,68,yes,hearing,no,,Craft,4\r\n13,Female,68,yes,hearing,no,,Running,5\r\n13,Female,68,yes,hearing,no,,Basketball,4\r\n13,Female,68,yes,hearing,no,,Football,3\r\n13,Female,68,yes,hearing,no,,Volleyball,5\r\n13,Female,68,yes,hearing,no,,Cricket,3\r\n13,Female,68,yes,hearing,no,,Hockey,1\r\n13,Female,68,yes,hearing,no,,Badminton,3\r\n13,Female,68,yes,hearing,no,,Tennis,2\r\n13,Female,68,yes,hearing,no,,Table Tennis,3\r\n13,Female,68,yes,hearing,no,,Attend Workshops or Conference,0\r\n13,Female,68,yes,hearing,no,,Woodworking Class,3\r\n13,Female,68,yes,hearing,no,,Pottery Class,2\r\n13,Female,68,yes,hearing,no,,Movie,0\r\n13,Female,68,yes,hearing,no,,Game night,2\r\n13,Female,68,yes,hearing,no,,Dance,2\r\n13,Female,68,yes,hearing,no,,Music,0\r\n13,Female,68,yes,hearing,no,,Yoga and Acrobatics,5\r\n13,Female,68,yes,hearing,no,,Community Gardening,5\r\n16,Male,21,yes,visual,no,,Board games,2\r\n16,Male,21,yes,visual,no,,Cooking,1\r\n16,Male,21,yes,visual,no,,Walking,5\r\n16,Male,21,yes,visual,no,,Reading,0\r\n16,Male,21,yes,visual,no,,Puzzles,2\r\n16,Male,21,yes,visual,no,,Craft,3\r\n16,Male,21,yes,visual,no,,Running,3\r\n16,Male,21,yes,visual,no,,Basketball,0\r\n16,Male,21,yes,visual,no,,Football,0\r\n16,Male,21,yes,visual,no,,Volleyball,0\r\n16,Male,21,yes,visual,no,,Cricket,0\r\n16,Male,21,yes,visual,no,,Hockey,0\r\n16,Male,21,yes,visual,no,,Badminton,0\r\n16,Male,21,yes,visual,no,,Tennis,0\r\n16,Male,21,yes,visual,no,,Table Tennis,0\r\n16,Male,21,yes,visual,no,,Attend Workshops or Conference,3\r\n16,Male,21,yes,visual,no,,Woodworking Class,0\r\n16,Male,21,yes,visual,no,,Pottery Class,2\r\n16,Male,21,yes,visual,no,,Movie,0\r\n16,Male,21,yes,visual,no,,Game night,2\r\n16,Male,21,yes,visual,no,,Dance,3\r\n16,Male,21,yes,visual,no,,Music,4\r\n16,Male,21,yes,visual,no,,Yoga and Acrobatics,2\r\n16,Male,21,yes,visual,no,,Community Gardening,1\r\n'}

In [6]:
user = pd.read_csv('Book3.csv')

In [7]:
user

,user,gender,age,disability,disability_type,mental_illness,illness_type,activity,rating
0,1,Female,18,no,NaN,yes,depression,Board games,3
1,1,Female,18,no,NaN,yes,depression,Cooking,4
2,1,Female,18,no,NaN,yes,depression,Walking,5
3,1,Female,18,no,NaN,yes,depression,Reading,4
4,1,Female,18,no,NaN,yes,depression,Puzzles,3
...,...,...,...,...,...,...,...,...,...
271,16,Male,21,yes,visual,no,NaN,Game night,2
272,16,Male,21,yes,visual,no,NaN,Dance,3
273,16,Male,21,yes,visual,no,NaN,Music,4
274,16,Male,21,yes,visual,no,NaN,Yoga and Acrobatics,2
275,16,Male,21,yes,visual,no,NaN,Community Gardening,1

In [8]:
from google.colab import files
files.upload()

Saving Book2.csv to Book2.csv

{'Book2.csv': b'\xef\xbb\xbfactivity,cognitive,physical,social,cultural,description\r\nBoard games,1,0,0,0,"This refers to a group of games played on a board, typically involving strategy, chance, and/or skill. Examples include Monopoly, Chess, Scrabble, and Settlers of Catan."\r\nCooking,1,0,0,0,"This involves the preparation and cooking of food, either as a hobby or a profession. It can involve experimenting with new recipes, trying out new techniques, and using different ingredients."\r\nWalking,1,0,0,0,"This refers to the activity of taking a leisurely walk, either alone or with others. It can be done for exercise, relaxation, or to explore one\'s surroundings."\r\nReading,1,0,0,0,"This involves the act of reading books, magazines, or other written material for pleasure, knowledge, or information."\r\nPuzzles,1,0,0,0,"This refers to games or activities that involve solving problems, usually in the form of a puzzle. Examples include jigsaw puzzles, crossword puzzles, and Sudoku."\r\nCraft,1,0,0,0,"This involves creating handmade items using various materials, such as paper, fabric, or wood. Examples include knitting, sewing, scrapbooking, and woodworking."\r\nRunning,0,1,0,0,"This involves jogging or running at a steady pace, either as a form of exercise or for competition."\r\nBasketball,0,1,0,0,"This is a team sport that involves two teams of five players each, trying to score points by shooting a ball through a hoop."\r\nFootball,0,1,0,0,"This is a team sport that involves two teams of eleven players each, trying to score points by kicking a ball into the opposing team\'s goal."\r\nVolleyball,0,1,0,0,"This is a team sport that involves two teams of six players each, trying to score points by hitting a ball over a net and into the opposing team\'s court."\r\nCricket,0,1,0,0,"This is a sport that involves two teams of eleven players each, trying to score points by hitting a ball with a bat and running between wickets."\r\nHockey,0,1,0,0,"This is a sport that involves two teams of players, trying to score points by hitting a puck into the opposing team\'s net using a stick."\r\nBadminton,0,1,0,0,"This is a sport that involves two or four players, trying to hit a shuttlecock over a net and onto the opposing team\'s side of the court."\r\nTennis,0,1,0,0,"This is a sport that involves two or four players, trying to hit a ball over a net and onto the opposing team\'s side of the court."\r\nTable Tennis,0,1,0,0,"This is a sport that involves two or four players, trying to hit a small ball over a net and onto the opposing team\'s side of a table."\r\nAttend Workshops or Conference,0,0,1,0,"This involves attending events where individuals can learn new skills, network with others in their field, and gain new knowledge and insights."\r\nWoodworking Class,0,0,1,0,"This involves taking classes to learn how to work with wood and create various items, such as furniture or decorative objects."\r\nPottery Class,0,0,1,0,"This involves taking classes to learn how to work with clay and create various pottery items, such as bowls, plates, and vases."\r\nMovie,0,0,1,0,"This involves watching a film, either at home or at a movie theater, for entertainment or educational purposes."\r\nGame night,0,0,1,0,"This involves getting together with friends or family to play games, such as board games, card games, or video games."\r\nDance,0,0,0,1,"This involves moving the body to music, either as a form of self-expression or for social and cultural purposes."\r\nMusic,0,0,0,1,"This involves listening to or playing music, either as a form of entertainment or for therapeutic purposes."\r\nYoga and Acrobatics,0,0,0,1,This involves practicing various yoga poses and/or acrobatic movements to improve physical and mental health.\r\nCommunity Gardening,0,0,0,1,"This involves working with others in a community garden to grow fruits, vegetables, or flowers, either for personal consumption or for donation to local charities or food banks."\r\n'}

In [9]:
activity = pd.read_csv('Book2.csv')

In [10]:
activity

,activity,cognitive,physical,social,cultural,description
0,Board games,1,0,0,0,This refers to a group of games played on a bo...
1,Cooking,1,0,0,0,This involves the preparation and cooking of f...
2,Walking,1,0,0,0,This refers to the activity of taking a leisur...
3,Reading,1,0,0,0,"This involves the act of reading books, magazi..."
4,Puzzles,1,0,0,0,This refers to games or activities that involv...
5,Craft,1,0,0,0,This involves creating handmade items using va...
6,Running,0,1,0,0,This involves jogging or running at a steady p...
7,Basketball,0,1,0,0,This is a team sport that involves two teams o...
8,Football,0,1,0,0,This is a team sport that involves two teams o...
9,Volleyball,0,1,0,0,This is a team sport that involves two teams o...
10,Cricket,0,1,0,0,This is a sport that involves two teams of ele...
11,Hockey,0,1,0,0,This is a sport that involves two teams of pla...
12,Badminton,0,1,0,0,This is a sport that involves two or four play...
13,Tennis,0,1,0,0,This is a sport that involves two or four play...
14,Table Tennis,0,1,0,0,This is a sport that involves two or four play...
15,Attend Workshops or Conference,0,0,1,0,This involves attending events where individua...
16,Woodworking Class,0,0,1,0,This involves taking classes to learn how to w...
17,Pottery Class,0,0,1,0,This involves taking classes to learn how to w...
18,Movie,0,0,1,0,"This involves watching a film, either at home ..."
19,Game night,0,0,1,0,This involves getting together with friends or...
20,Dance,0,0,0,1,"This involves moving the body to music, either..."
21,Music,0,0,0,1,"This involves listening to or playing music, e..."
22,Yoga and Acrobatics,0,0,0,1,This involves practicing various yoga poses an...
23,Community Gardening,0,0,0,1,This involves working with others in a communi...

In [11]:
specific_rows = [0,192]

#import specific rows from CSV into DataFrame
df = pd.read_csv('Book3.csv', skiprows = lambda x: x not in specific_rows)

In [12]:
df

,user,gender,age,disability,disability_type,mental_illness,illness_type,activity,rating
0,12,Female,47,yes,mobility,yes,anxiety,Walking,2

# **Discard the activities based on the type of mental illness**

In [13]:
list1= []
count = 0
list2= []

if df.mental_illness[0] == 'yes':
  if df.illness_type[0] == 'anxiety':
    while count <24:
      list1.append(activity.cognitive[count])
      list1.append(activity.physical[count])
      list1.append(activity.social[count])
      list1.append(activity.cultural[count])
      if (list1 == [1,0,0,0]) | (list1 == [0,1,0,0]):
        list2.append(activity.activity[count])
        print(activity.activity[count])
      count = count+1 
      list1 = []
  elif df.illness_type[0] == 'depression':
    while count <24:
      list1.append(activity.cognitive[count])
      list1.append(activity.physical[count])
      list1.append(activity.social[count])
      list1.append(activity.cultural[count])
      if (list1 == [1,0,0,0]) | (list1 == [0,1,0,0]) | (list1 == [0,0,1,0]) | (list1 == [0,0,0,1]) :
        list2.append(activity.activity[count])
        print(activity.activity[count])
      count = count+1 
      list1 = []
  elif df.illness_type[0] == 'neurodevelopmental':
    while count <24:
      list1.append(activity.cognitive[count])
      list1.append(activity.physical[count])
      list1.append(activity.social[count])
      list1.append(activity.cultural[count])
      if list1 == [1,0,0,0]:
        list2.append(activity.activity[count])
        print(activity.activity[count])
      count = count+1 
      list1 = []
elif df.mental_illness[0] == 'no':
  while count <24:
      list1.append(activity.cognitive[count])
      list1.append(activity.physical[count])
      list1.append(activity.social[count])
      list1.append(activity.cultural[count])
      if (list1 == [1,0,0,0]) | (list1 == [0,1,0,0]) | (list1 == [0,0,1,0]) | (list1 == [0,0,0,1]):  
        list2.append(activity.activity[count])
        print(activity.activity[count])
      count = count+1 
      list1 = []

Board games
Cooking
Walking
Reading
Puzzles
Craft
Running
Basketball
Football
Volleyball
Cricket
Hockey
Badminton
Tennis
Table Tennis

# **Make a new dataframe with just the filtered activities and ratings for all users for that particular activity**

In [14]:
new_df = user[['user','activity','rating']].copy()

In [15]:
length = len(list2)
length_set = len(new_df)
new_new_df = pd.DataFrame({'user':[],'activity':[],'rating':[]})

dict_list = []

for i in range(0,length-1):
  for j in range(0,length_set-1):
    if new_df.activity[j] == list2[i]:
      row_dict = { 'user': new_df.user[j], 'activity' : new_df.activity[j], 'rating' : new_df.rating[j] }
      dict_list.append(row_dict)

new_new_df = pd.DataFrame.from_dict(dict_list)

print(new_new_df)

     user     activity  rating
0       1  Board games       3
1       2  Board games       4
2       4  Board games       2
3       7  Board games       3
4       8  Board games       2
..    ...          ...     ...
187    11       Tennis       0
188    12       Tennis       0
189    15       Tennis       0
190    13       Tennis       2
191    16       Tennis       0

[192 rows x 3 columns]

In [16]:
user_ratings = new_new_df.pivot_table(index = {'user'}, columns = {'activity'}, values = 'rating')
user_ratings.head()

activity,Badminton,Basketball,Board games,Cooking,Craft,Cricket,Football,Hockey,Puzzles,Reading,Running,Tennis,Volleyball,Walking
user,,,,,,,,,,,,,,
1,4.0,4.0,3.0,4.0,4.0,3.0,4.0,3.0,3.0,4.0,5.0,4.0,4.0,5.0
2,4.0,5.0,4.0,3.0,2.0,4.0,4.0,4.0,2.0,3.0,5.0,5.0,5.0,3.0
3,NaN,NaN,4.0,3.0,5.0,NaN,NaN,NaN,4.0,0.0,NaN,NaN,NaN,2.0
4,0.0,0.0,2.0,3.0,2.0,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0,5.0
5,0.0,0.0,1.0,2.0,2.0,0.0,0.0,0.0,1.0,0.0,5.0,0.0,0.0,4.0

# **Use collaborative filtering**

In [17]:
user_ratings = user_ratings.fillna(0)
user_ratings

activity,Badminton,Basketball,Board games,Cooking,Craft,Cricket,Football,Hockey,Puzzles,Reading,Running,Tennis,Volleyball,Walking
user,,,,,,,,,,,,,,
1,4.0,4.0,3.0,4.0,4.0,3.0,4.0,3.0,3.0,4.0,5.0,4.0,4.0,5.0
2,4.0,5.0,4.0,3.0,2.0,4.0,4.0,4.0,2.0,3.0,5.0,5.0,5.0,3.0
3,0.0,0.0,4.0,3.0,5.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,2.0
4,0.0,0.0,2.0,3.0,2.0,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0,5.0
5,0.0,0.0,1.0,2.0,2.0,0.0,0.0,0.0,1.0,0.0,5.0,0.0,0.0,4.0
6,0.0,0.0,3.0,4.0,4.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,4.0
7,0.0,0.0,3.0,4.0,4.0,0.0,0.0,0.0,4.0,5.0,0.0,0.0,0.0,5.0
8,3.0,4.0,2.0,2.0,2.0,3.0,5.0,2.0,4.0,5.0,5.0,5.0,5.0,4.0
9,4.0,2.0,3.0,4.0,1.0,4.0,3.0,3.0,4.0,5.0,1.0,5.0,4.0,3.0
10,4.0,3.0,3.0,4.0,5.0,2.0,2.0,5.0,3.0,4.0,4.0,2.0,4.0,5.0
11,1.0,0.0,4.0,3.0,3.0,1.0,0.0,0.0,4.0,5.0,0.0,0.0,0.0,1.0
12,0.0,0.0,1.0,4.0,3.0,0.0,0.0,0.0,5.0,5.0,0.0,0.0,0.0,2.0
13,3.0,4.0,2.0,3.0,4.0,3.0,3.0,1.0,3.0,4.0,5.0,2.0,5.0,5.0
14,0.0,0.0,5.0,3.0,5.0,0.0,0.0,0.0,3.0,4.0,0.0,0.0,0.0,1.0
15,0.0,0.0,5.0,4.0,2.0,0.0,0.0,0.0,2.0,3.0,0.0,0.0,0.0,0.0
16,0.0,0.0,2.0,1.0,3.0,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0,5.0

In [18]:
# Normalize user-item matrix
matrix_norm = user_ratings.subtract(user_ratings.mean(axis=1), axis = 'rows')
matrix_norm.head()

activity,Badminton,Basketball,Board games,Cooking,Craft,Cricket,Football,Hockey,Puzzles,Reading,Running,Tennis,Volleyball,Walking
user,,,,,,,,,,,,,,
1,0.142857,0.142857,-0.857143,0.142857,0.142857,-0.857143,0.142857,-0.857143,-0.857143,0.142857,1.142857,0.142857,0.142857,1.142857
2,0.214286,1.214286,0.214286,-0.785714,-1.785714,0.214286,0.214286,0.214286,-1.785714,-0.785714,1.214286,1.214286,1.214286,-0.785714
3,-1.285714,-1.285714,2.714286,1.714286,3.714286,-1.285714,-1.285714,-1.285714,2.714286,-1.285714,-1.285714,-1.285714,-1.285714,0.714286
4,-1.214286,-1.214286,0.785714,1.785714,0.785714,-1.214286,-1.214286,-1.214286,0.785714,-1.214286,1.785714,-1.214286,-1.214286,3.785714
5,-1.071429,-1.071429,-0.071429,0.928571,0.928571,-1.071429,-1.071429,-1.071429,-0.071429,-1.071429,3.928571,-1.071429,-1.071429,2.928571

In [19]:
# User similarity matrix using Pearson correlation
user_similarity = matrix_norm.T.corr()
user_similarity.head()

user,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
user,,,,,,,,,,,,,,,,
1,1.000000,0.173492,-0.209529,0.458802,0.647158,0.176869,0.083247,0.480074,-0.314054,0.334719,-0.308327,-0.066667,0.736212,-0.228772,-0.312940,0.452863
2,0.173492,1.000000,-0.738048,-0.421309,-0.169053,-0.695925,-0.823595,0.397005,-0.008255,-0.355146,-0.732302,-0.835916,0.004301,-0.703597,-0.484596,-0.435047
3,-0.209529,-0.738048,1.000000,0.576794,0.314278,0.718427,0.700353,-0.557320,-0.260472,0.249718,0.658703,0.596576,-0.047610,0.818878,0.682194,0.589455
4,0.458802,-0.421309,0.576794,1.000000,0.888690,0.662468,0.618821,-0.182557,-0.368227,0.446748,0.240391,0.373838,0.386426,0.338207,0.286188,0.927638
5,0.647158,-0.169053,0.314278,0.888690,1.000000,0.412289,0.347428,0.013120,-0.566328,0.449233,0.011004,0.155048,0.526627,0.127232,0.049863,0.870063

In [20]:
# Remove the person with user ID 12
user_similarity.drop(index=12, inplace=True)
user_similarity.head()

user,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
user,,,,,,,,,,,,,,,,
1,1.000000,0.173492,-0.209529,0.458802,0.647158,0.176869,0.083247,0.480074,-0.314054,0.334719,-0.308327,-0.066667,0.736212,-0.228772,-0.312940,0.452863
2,0.173492,1.000000,-0.738048,-0.421309,-0.169053,-0.695925,-0.823595,0.397005,-0.008255,-0.355146,-0.732302,-0.835916,0.004301,-0.703597,-0.484596,-0.435047
3,-0.209529,-0.738048,1.000000,0.576794,0.314278,0.718427,0.700353,-0.557320,-0.260472,0.249718,0.658703,0.596576,-0.047610,0.818878,0.682194,0.589455
4,0.458802,-0.421309,0.576794,1.000000,0.888690,0.662468,0.618821,-0.182557,-0.368227,0.446748,0.240391,0.373838,0.386426,0.338207,0.286188,0.927638
5,0.647158,-0.169053,0.314278,0.888690,1.000000,0.412289,0.347428,0.013120,-0.566328,0.449233,0.011004,0.155048,0.526627,0.127232,0.049863,0.870063

In [21]:
 # User similarity threashold of 0.4 or more
# Get top 4 similar users
drop_user = 12
similar_users = user_similarity[user_similarity[drop_user]>0.4][drop_user].sort_values(ascending=False)[:4]
# Print out top 4 similar users
print(f'The similar users for user {drop_user} are', similar_users)

The similar users for user 12 are user
7     0.887972
11    0.858480
14    0.743508
6     0.691960
Name: 12, dtype: float64

In [22]:
# activities that similar users have tried and discard the activities that none of the similar users have tried
similar_user_activity = matrix_norm[matrix_norm.index.isin(similar_users.index)].dropna(axis=1, how='all')
similar_user_activity

activity,Badminton,Basketball,Board games,Cooking,Craft,Cricket,Football,Hockey,Puzzles,Reading,Running,Tennis,Volleyball,Walking
user,,,,,,,,,,,,,,
6,-1.357143,-1.357143,1.642857,2.642857,2.642857,-1.357143,-1.357143,-1.357143,-0.357143,1.642857,-1.357143,-1.357143,-1.357143,2.642857
7,-1.785714,-1.785714,1.214286,2.214286,2.214286,-1.785714,-1.785714,-1.785714,2.214286,3.214286,-1.785714,-1.785714,-1.785714,3.214286
11,-0.571429,-1.571429,2.428571,1.428571,1.428571,-0.571429,-1.571429,-1.571429,2.428571,3.428571,-1.571429,-1.571429,-1.571429,-0.571429
14,-1.500000,-1.500000,3.500000,1.500000,3.500000,-1.500000,-1.500000,-1.500000,1.500000,2.500000,-1.500000,-1.500000,-1.500000,-0.500000

In [23]:
# A dictionary to store item scores
item_score = {}

for i in similar_user_activity.columns:
  activity_rating = similar_user_activity[i]
  total = 0
  count = 0
# score is the sum of user similarity score multiply by the activity rating then we add the score to the total score for the activity so far
  for j in similar_users.index:
    if pd.isna(activity_rating[j]) == False:
      score = similar_users[j] * activity_rating[j]
      total = total + score
      count = count + 1
# Get the average score for the item
  item_score[i] = total / count
    
# Convert dictionary to pandas dataframe where the activities are ranked by the score and print top 4 by score
item_score = pd.DataFrame(item_score.items(), columns=['activity', 'activity_score'])
ranked_item_score = item_score.sort_values( by = 'activity_score', ascending=False )
ranked_item_score.head(6)

       activity  activity_score
9       Reading        2.198279
4         Craft        1.905913
2   Board games        1.725550
3       Cooking        1.534159
8       Puzzles        1.229809
13      Walking        0.955158

# **Evaluation**

In [2]:
pip install scikit-surprise

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting scikit-surprise
  Downloading scikit-surprise-1.1.3.tar.gz (771 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 772.0/772.0 kB 11.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: joblib>=1.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-surprise) (1.2.0)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.9/dist-packages (from scikit-surprise) (1.22.4)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.9/dist-packages (from scikit-surprise) (1.10.1)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (setup.py) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.3-cp39-cp39-linux_x86_64.whl size=3195788 sha256=ce4e32065a38b1c329520a73fb35c6291179c6043e4f6a6110cee7e5b1377e3d
  Stored in directory: /root/.cache/pip/wheels/c6/3a/46/9b17b3512bdf283c6cb84f59929cdd5199d4e754d596d22784
Successfully built scikit-surprise
Installing collected packages: scikit-surprise
Successfully installed scikit-surprise-1.1.3

In [7]:
import pandas as pd
from surprise import Dataset, Reader, SVD
from surprise.model_selection import cross_validate
from surprise.accuracy import rmse

# Load data from a DataFrame
df = pd.read_csv('Book3.csv')

# Define the rating scale
reader = Reader(rating_scale=(1, 5))

# Load data into Surprise dataset
data = Dataset.load_from_df(df[['user', 'activity', 'rating']], reader)

# Define the SVD algorithm
algo = SVD()

# Evaluate the algorithm using RMSE metric
cv_results = cross_validate(algo, data, measures=['RMSE','MAE'], cv=5, verbose=True)

# Print the average RMSE score
print("Average RMSE score:", cv_results['test_rmse'].mean())
print("Average MAE score:", cv_results['test_mae'].mean())

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std
RMSE (testset)    1.5342  1.5615  1.5032  1.5385  1.5774  1.5429  0.0253
MAE (testset)     1.2474  1.3222  1.2770  1.3202  1.3841  1.3102  0.0464
Fit time          0.00    0.00    0.00    0.00    0.00    0.00    0.00
Test time         0.00    0.00    0.00    0.00    0.00    0.00    0.00
Average RMSE score: 1.5429428499455848
Average MAE score: 1.3101887024893917

In [85]:
import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score

In [91]:
ground_truth = {'activity' : {'Board games', 'Cooking', 'Walking', 'Reading', 'Puzzles', 'Craft','Table Tennis'} }
predicted_labels = {'activity' : {'Reading', 'Craft', 'Board games', 'Cooking', 'Puzzles', 'Walking'}}

ground_truth = [0, 1, 2, 3, 4, 5, 14]
predicted_labels = [3, 5, 0, 1, 4, 2]

In [92]:
# Calculate the number of correctly recommended items
correct_recommendations = set(predicted_labels).intersection(set(ground_truth))
num_correct_recommendations = len(correct_recommendations)

# Calculate precision
precision = num_correct_recommendations / len(predicted_labels)

# Calculate recall
recall = num_correct_recommendations / len(ground_truth)

# Calculate F1-score
f1_score = 2 * (precision * recall) / (precision + recall)

# Print the evaluation metrics
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1_score)

Precision: 1.0
Recall: 0.8571428571428571
F1-score: 0.923076923076923

This code will output the average RMSE score for the collaborative filtering recommender system. A lower RMSE score indicates better performance of the recommender system.